BookCollection/Models/BookCollectionViewModels.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BookCollection.Models
{
    public class BookCollectionViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int NumberOfBooks { get; set; }
        public List<Book> Books {get;set;}

        public void calculateNumberOfBooks()
        {
            NumberOfBooks = Books.Count();
        }
    }

    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PublishYear { get; set; }
    }
}

BookCollection/Controllers/BookCollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookCollection.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace BookCollection.Controllers
{
    [Authorize]
    public class BookCollectionController : Controller
    {
        private DefaultConnectionEntities db = new DefaultConnectionEntities();

        private List<BookCollectionViewModel> _data = new List<BookCollectionViewModel>
        {
            new BookCollectionViewModel
            {
                Id = 1,
                Name = "Disney Books",
                Books = new List<Book> { new Book { Id=001, Name="Snehvide", PublishYear="1970"}, new Book { Id=002, Name="Tornerose", PublishYear="1974"} }
            },

            new BookCollectionViewModel
            {
                Id = 2,
                Name = "Animal Books",
                Books = new List<Book> { new Book { Id = 001, Name = "Havet er skønt", PublishYear = "1970" } }
            }
        };

        public BookCollectionController()
        {
            foreach(var item in _data)
            {
                item.calculateNumberOfBooks();
            }
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: BookCollection
        public ActionResult Index()
        {
            var userId = UserManager.FindById(User.Identity.GetUserId()).Id;

            var model = db.BooklistDetailView.Where(m => m.Id == userId);
           
            return View(model);
        }

        // GET: BookCollection/Details/1
        public ActionResult Details(int? booklistId)
        {
            if (booklistId != null)
            {
                var model = db.BooklistDetailView.Where(m => m.Id == UserId && m.booklistId == booklistId);

                if(model.Count() > 0)
                {
                    return View(model);
                }
            }
            return RedirectToAction("Index");
        }

        // GET: BookCollection/CreateNewBooklist
        public ActionResult CreateNewBooklist()
        {
            return View();
        }

        // POST: BookCollection/CreateNewBooklist
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateNewBooklist(BookCollectionViewModel model)
        {
            var newBooklist = new Booklists { booklistName = model.Name };
            var booklist = db.Booklists.Add(newBooklist);

            var newLink = new linkAspNetUsersBooklists { aspNetUserId = UserId, booklistId = booklist.booklistId };
            db.linkAspNetUsersBooklists.Add(newLink);

            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET: BookCollection/CreateNewBook
        public ActionResult CreateNewBook(int? booklistId)
        {
            if(booklistId != null)
            {
                ViewBag.booklistId = booklistId;
                return View();
            }
            return RedirectToAction("Index");
        }

        // POST: BookCollection/CreateNewBook
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateNewBook(Books model, int? booklistId)
        {
            if(model != null && booklistId != null)
            {
                var newBook = db.Books.Add(model);
                var newLink = new linkBooklistsBooks { bookId = newBook.bookId, booklistId = (int)booklistId };
                db.linkBooklistsBooks.Add(newLink);

                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { booklistId = booklistId });
            }

            return RedirectToAction("Index");
        }


        // POST: BookCollection/ToggleBookOwned
        [HttpPost]
        public ActionResult ToggleBookOwned(int id)
        {
            Books book = db.Books.Where(m => m.bookId == id).FirstOrDefault();

            book.bookOwned = !book.bookOwned;
            db.SaveChanges();
            return null;
        }

        #region Helpers

        public string UserId { get { return UserManager.FindById(User.Identity.GetUserId()).Id; } }

        #endregion
    }
}

BookCollection/Views/BookCollection/CreateNewBook.cshtml
@model BookCollection.Models.Books
@{
    ViewBag.Title = "Add new Book";
}

<div class="regSite">
    <div class="jumbotron">
        @using (Html.BeginForm("CreateNewBook", "BookCollection", new { booklistId = ViewBag.booklistId }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <h4>Add new Book</h4>
            <hr />
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.bookName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.bookName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.bookPublishYear, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.bookPublishYear, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.bookEANNumber, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.bookEANNumber, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Register" />
                </div>
            </div>
        }
    </div>
</div>

BookCollection/Views/BookCollection/CreateNewBooklist.cshtml
@model BookCollection.Models.BookCollectionViewModel
@{
    ViewBag.Title = "Create a new Booklist";
}

<div class="regSite">
    <div class="jumbotron">
        @using (Html.BeginForm("CreateNewBooklist", "BookCollection", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <h4>Create a new Booklist</h4>
            <hr />
            @Html.ValidationSummary("", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Register" />
                </div>
            </div>
        }
    </div>
</div>

BookCollection/Views/BookCollection/Details.cshtml
@model DbQuery<BookCollection.Models.BooklistDetailView>
@{
    ViewBag.Title = "Details";
}


<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            @Html.ActionLink("Back", "index", "BookCollection")
            <h2>@Model.FirstOrDefault().booklistName</h2>
            <p>Id: @Model.FirstOrDefault().booklistId</p>
            <p>Number of books: @Model.Count()</p>
        </div>
        <div class="col-md-8">
            <h2>Books</h2>
            @Html.ActionLink("Add new book", "CreateNewBook", "BookCollection", new { booklistId = Model.FirstOrDefault().booklistId }, null)
            <div class="row">
                <div class="col-md-1">
                    <b>#</b>
                </div>
                <div class="col-md-23">
                    <b>Book Name</b>
                </div>
            </div>
                    
            @foreach (var book in Model.Select(m => new { m.bookId, m.bookName, m.bookPublishYear, m.bookEANNumber, m.bookOwned }).Distinct())
            {

                <div class="rows">
                    <div class="col-md-1">
                        @Html.CheckBox("bookOwned", (bool)book.bookOwned ? true : false, new { onClick= "SubForm(" + book.bookId + ")" })
                    </div>
                    <div class="col-md-23">
                        @book.bookName
                    </div>
                </div>
            }

            <hr />

            </div>

    </div>
</div>

BookCollection/Views/BookCollection/Index.cshtml
@model DbQuery<BookCollection.Models.BooklistDetailView>
@{
    ViewBag.Title = "Book Lists";
}

<div class="regSite">
    <div class="jumbotron">
        <h2>@ViewBag.Title</h2>

        <hr />

        <div class="row">
            <div class="col-md-4">
                <b>Name</b>
            </div>
            <div class="col-md-4">
                <b>Number of books</b>
            </div>
        </div>
        @foreach (var item in Model.Select(m => new { m.booklistId, m.booklistName }).Distinct())
        {
            <div class="row">
                <div class="col-md-4">
                    <p>@Html.ActionLink(item.booklistName, "Details", "BookCollection", new { booklistId = item.booklistId }, null)</p>
                </div>
                <div class="col-md-4">
                    <p>@Model.Where(m => m.booklistId == item.booklistId && m.bookName != null).Count()</p>
                </div>
            </div>
        }

        <hr />

        @Html.ActionLink("Add new book List", "CreateNewBooklist", "BookCollection")
    </div>
</div>